@startuml

class GameSystem
{
	-entities
	-world
	-is_play
	-step
	-physics_step
	-lag
	-physics_multiplier
	-trigger
	+widget()
	+play()
	+pause()
	+step()
	+speed_up()
	+speed_down()
	-run()
	-create_world()
	-create_creature()
}

@enduml