@startuml

interface IGameEntity
{
	-icontroller
	-iphysics
	-irender
	+IGameEntity(icontroller, iphysics, irender)
	+controller()
	+physics()
	+render()
}

interface IPhysicsStrategy
{
	+update(i_game_entity, world, dt)
}

interface IRenderStrategy
{
	+render(i_game_entity, render)
}

@enduml